apiVersion: v1
stringData:
  POSTGRES_PASSWORD: oAsQgKy7Os4wxcyzxTZK2A0t9KuNnjtcgiwB7Nf3nklpGxjdxVSyAsR0ucpDjU8z
  DATABASE_URL: postgresql://retreat_2026_deploy:oAsQgKy7Os4wxcyzxTZK2A0t9KuNnjtcgiwB7Nf3nklpGxjdxVSyAsR0ucpDjU8z@postgres/retreat_2026_deploy
  DJANGO_SECRET_KEY: 7LW7QJ22zHJHYTCqiNscLarttpYeE3RTQl5jRRbQe0D7ST6ZrgfZTnCPwYFydK9z
kind: Secret
metadata:
  name: secrets-config
type: Opaque
